spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_second_kill?characterEncoding=utf8 &serverTimezone=GMT%2B8
    username: root
    password: '0730'
  redis:
    database: 0
    host: 192.168.32.129
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000
  rabbitmq:
    host: 192.168.32.129
    port: 5672
    username: guest
    password: guest

mybatis:
  mapperLocations: classpath:mapper/mappers/*.xml
  config-location: classpath:mapper/mybatis-config.xml
  typeAliasesPackage: com.thesoul.shopkill.entity
server:
  port: 8001
